# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/UI_board_write.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_board_write_widget(object):
    def setupUi(self, board_write_widget):
        board_write_widget.setObjectName("board_write_widget")
        board_write_widget.resize(702, 380)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(board_write_widget.sizePolicy().hasHeightForWidth())
        board_write_widget.setSizePolicy(sizePolicy)
        board_write_widget.setMinimumSize(QtCore.QSize(0, 380))
        self.verticalLayout = QtWidgets.QVBoxLayout(board_write_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(board_write_widget)
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"                background: transparent;\n"
"                width: 15px;\n"
"                margin: 0px;\n"
"            }\n"
"            \n"
"            QScrollBar:horizontal {\n"
"                background: transparent;\n"
"                height: 15px;\n"
"                margin: 0px;\n"
"            }\n"
"            \n"
"            QScrollBar::handle:vertical {\n"
"                background: #FFFFFF;  /* 하얀색 테두리 */\n"
"                border: 2px solid #2F80ED;  /* 파란색 테두리 */\n"
"                min-height: 20px;\n"
"                border-radius: 5px;  /* 테두리 깍기 */\n"
"                min-height: 20px;\n"
"            }\n"
"            QScrollBar::handle:vertical:hover{    \n"
"            background-color: #2F80ED;\n"
"            }\n"
"            QScrollBar::handle:vertical:pressed {    \n"
"            background-color: #2F80ED;\n"
"            }\n"
"            \n"
"            QScrollBar::handle:horizontal {\n"
"                background: #FFFFFF;  /* 하얀색 테두리 */\n"
"                border: 5px solid #2F80ED;  /* 파란색 테두리 */\n"
"                min-width: 20px;\n"
"            }\n"
"            \n"
"            QScrollBar::add-line:vertical,\n"
"            QScrollBar::sub-line:vertical,\n"
"            QScrollBar::add-line:horizontal,\n"
"            QScrollBar::sub-line:horizontal {\n"
"                height: 0px;\n"
"                width: 0px;\n"
"            }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 700, 378))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.board_main_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.board_main_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.board_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.board_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.board_main_frame.setObjectName("board_main_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.board_main_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.board_main_frame)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(596, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.admit_btn = QtWidgets.QPushButton(self.widget)
        self.admit_btn.setObjectName("admit_btn")
        self.horizontalLayout_2.addWidget(self.admit_btn)
        self.verticalLayout_4.addWidget(self.widget)
        self.title_widget = QtWidgets.QWidget(self.board_main_frame)
        self.title_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.title_widget.setObjectName("title_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.title_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.title_lineedit = QtWidgets.QLineEdit(self.title_widget)
        self.title_lineedit.setMinimumSize(QtCore.QSize(0, 30))
        self.title_lineedit.setObjectName("title_lineedit")
        self.verticalLayout_3.addWidget(self.title_lineedit)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.img_lab = QtWidgets.QLabel(self.title_widget)
        self.img_lab.setText("")
        self.img_lab.setObjectName("img_lab")
        self.horizontalLayout_4.addWidget(self.img_lab)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem3)
        self.contents_textedit = QtWidgets.QTextEdit(self.title_widget)
        self.contents_textedit.setObjectName("contents_textedit")
        self.verticalLayout_3.addWidget(self.contents_textedit)
        self.verticalLayout_4.addWidget(self.title_widget)
        self.widget_3 = QtWidgets.QWidget(self.board_main_frame)
        self.widget_3.setMinimumSize(QtCore.QSize(680, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(700, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.img_upload_btn = QtWidgets.QPushButton(self.widget_3)
        self.img_upload_btn.setMinimumSize(QtCore.QSize(100, 0))
        self.img_upload_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.img_upload_btn.setObjectName("img_upload_btn")
        self.horizontalLayout_3.addWidget(self.img_upload_btn)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.verticalLayout_2.addWidget(self.board_main_frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(board_write_widget)
        QtCore.QMetaObject.connectSlotsByName(board_write_widget)

    def retranslateUi(self, board_write_widget):
        _translate = QtCore.QCoreApplication.translate
        board_write_widget.setWindowTitle(_translate("board_write_widget", "Form"))
        self.admit_btn.setText(_translate("board_write_widget", "등록"))
        self.title_lineedit.setPlaceholderText(_translate("board_write_widget", "제목을 입력해 주세요."))
        self.contents_textedit.setPlaceholderText(_translate("board_write_widget", "여기에 작성글을 업로드하세요."))
        self.img_upload_btn.setText(_translate("board_write_widget", "이미지 업로드"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    board_write_widget = QtWidgets.QWidget()
    ui = Ui_board_write_widget()
    ui.setupUi(board_write_widget)
    board_write_widget.show()
    sys.exit(app.exec_())
