# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/UI_board_read.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_board_read_widget(object):
    def setupUi(self, board_read_widget):
        board_read_widget.setObjectName("board_read_widget")
        board_read_widget.resize(702, 380)
        board_read_widget.setMinimumSize(QtCore.QSize(0, 380))
        self.verticalLayout = QtWidgets.QVBoxLayout(board_read_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(board_read_widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 700, 378))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.board_main_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.board_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.board_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.board_main_frame.setObjectName("board_main_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.board_main_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.title_widget = QtWidgets.QWidget(self.board_main_frame)
        self.title_widget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.title_widget.setObjectName("title_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.writer_lab = QtWidgets.QLabel(self.title_widget)
        self.writer_lab.setObjectName("writer_lab")
        self.horizontalLayout.addWidget(self.writer_lab)
        self.write_time_lab = QtWidgets.QLabel(self.title_widget)
        self.write_time_lab.setObjectName("write_time_lab")
        self.horizontalLayout.addWidget(self.write_time_lab)
        self.read_cnt_lab = QtWidgets.QLabel(self.title_widget)
        self.read_cnt_lab.setObjectName("read_cnt_lab")
        self.horizontalLayout.addWidget(self.read_cnt_lab)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.commnets_cnt_lab = QtWidgets.QLabel(self.title_widget)
        self.commnets_cnt_lab.setObjectName("commnets_cnt_lab")
        self.horizontalLayout.addWidget(self.commnets_cnt_lab)
        self.verticalLayout_4.addWidget(self.title_widget)
        self.widget_2 = QtWidgets.QWidget(self.board_main_frame)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.img_lab = QtWidgets.QLabel(self.widget_2)
        self.img_lab.setObjectName("img_lab")
        self.verticalLayout_3.addWidget(self.img_lab)
        self.contents_lab = QtWidgets.QLabel(self.widget_2)
        self.contents_lab.setObjectName("contents_lab")
        self.verticalLayout_3.addWidget(self.contents_lab)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.board_main_frame)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(344, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_5.addWidget(self.widget_3)
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.verticalLayout_4.addWidget(self.widget)
        self.verticalLayout_2.addWidget(self.board_main_frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(board_read_widget)
        QtCore.QMetaObject.connectSlotsByName(board_read_widget)

    def retranslateUi(self, board_read_widget):
        _translate = QtCore.QCoreApplication.translate
        board_read_widget.setWindowTitle(_translate("board_read_widget", "Form"))
        self.writer_lab.setText(_translate("board_read_widget", "글쓴이"))
        self.write_time_lab.setText(_translate("board_read_widget", "작성시간"))
        self.read_cnt_lab.setText(_translate("board_read_widget", "조회수"))
        self.commnets_cnt_lab.setText(_translate("board_read_widget", "댓글수"))
        self.img_lab.setText(_translate("board_read_widget", "사진"))
        self.contents_lab.setText(_translate("board_read_widget", "내용"))
        self.label.setText(_translate("board_read_widget", "댓글 보기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    board_read_widget = QtWidgets.QWidget()
    ui = Ui_board_read_widget()
    ui.setupUi(board_read_widget)
    board_read_widget.show()
    sys.exit(app.exec_())
