# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/UI_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 30)
        Form.setMinimumSize(QtCore.QSize(0, 30))
        Form.setMaximumSize(QtCore.QSize(16777215, 30))
        Form.setStyleSheet("")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.List_frame = QtWidgets.QFrame(Form)
        self.List_frame.setStyleSheet("")
        self.List_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.List_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.List_frame.setObjectName("List_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.List_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.num_lab = QtWidgets.QLabel(self.List_frame)
        self.num_lab.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 네오 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.num_lab.setFont(font)
        self.num_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.num_lab.setObjectName("num_lab")
        self.horizontalLayout.addWidget(self.num_lab)
        self.title_lab = QtWidgets.QLabel(self.List_frame)
        self.title_lab.setMinimumSize(QtCore.QSize(420, 0))
        self.title_lab.setMaximumSize(QtCore.QSize(420, 16777215))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 네오 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.title_lab.setFont(font)
        self.title_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.title_lab.setObjectName("title_lab")
        self.horizontalLayout.addWidget(self.title_lab)
        self.writer_lab = QtWidgets.QLabel(self.List_frame)
        self.writer_lab.setMinimumSize(QtCore.QSize(70, 0))
        self.writer_lab.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 네오 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.writer_lab.setFont(font)
        self.writer_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.writer_lab.setObjectName("writer_lab")
        self.horizontalLayout.addWidget(self.writer_lab)
        self.date_lab = QtWidgets.QLabel(self.List_frame)
        self.date_lab.setMinimumSize(QtCore.QSize(107, 0))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 네오 Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.date_lab.setFont(font)
        self.date_lab.setStyleSheet("")
        self.date_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.date_lab.setObjectName("date_lab")
        self.horizontalLayout.addWidget(self.date_lab)
        self.horizontalLayout_2.addWidget(self.List_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.num_lab.setText(_translate("Form", "TextLabel"))
        self.title_lab.setText(_translate("Form", "TextLabel"))
        self.writer_lab.setText(_translate("Form", "이름"))
        self.date_lab.setText(_translate("Form", "날짜"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
