# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/UI_warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 360)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.titile_lab = QtWidgets.QLabel(Dialog)
        self.titile_lab.setMaximumSize(QtCore.QSize(16777215, 60))
        self.titile_lab.setStyleSheet("background-color: rgb(47, 128, 237);\n"
"border-top-left-radius:7px;\n"
"border-top-right-radius: 7px;")
        self.titile_lab.setText("")
        self.titile_lab.setObjectName("titile_lab")
        self.verticalLayout.addWidget(self.titile_lab)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.warning_lab = QtWidgets.QLabel(self.widget)
        self.warning_lab.setMinimumSize(QtCore.QSize(446, 192))
        self.warning_lab.setMaximumSize(QtCore.QSize(450, 16777215))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 네오 Regular")
        font.setPointSize(16)
        self.warning_lab.setFont(font)
        self.warning_lab.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.warning_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.warning_lab.setObjectName("warning_lab")
        self.verticalLayout_3.addWidget(self.warning_lab)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.yes_btn = QtWidgets.QPushButton(self.widget)
        self.yes_btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 네오 Regular")
        font.setPointSize(15)
        self.yes_btn.setFont(font)
        self.yes_btn.setStyleSheet("background-color: rgb(47, 128, 237);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 7px;")
        self.yes_btn.setObjectName("yes_btn")
        self.horizontalLayout_2.addWidget(self.yes_btn)
        self.no_btn = QtWidgets.QPushButton(self.widget)
        self.no_btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 네오 Regular")
        font.setPointSize(15)
        self.no_btn.setFont(font)
        self.no_btn.setStyleSheet("border-radius: 7px;\n"
"background-color: rgb(45, 45, 45);\n"
"color: rgb(255, 255, 255);")
        self.no_btn.setObjectName("no_btn")
        self.horizontalLayout_2.addWidget(self.no_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.widget)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.warning_lab.setText(_translate("Dialog", "여기에 경고 경고문구"))
        self.yes_btn.setText(_translate("Dialog", "예"))
        self.no_btn.setText(_translate("Dialog", "아니오"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
